In [2]:

import pandas as pd
import numpy as np

In [70]:
dataset = pd.read_csv(r"employee_2.csv")
dataset

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,171369.0
1,Bachelors,2013,Pune,1,28,Female,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,166478.0
4,Masters,2017,NaN,3,24,Male,Yes,2,1,393136.0
...,...,...,...,...,...,...,...,...,...,...
1802,Bachelors,2014,Bangalore,3,25,Female,No,3,0,257493.0
1803,Bachelors,2016,Bangalore,3,26,Female,No,4,0,208095.0
1804,Bachelors,2016,Bangalore,3,26,Female,No,4,0,97346.0
1805,Bachelors,2014,New Delhi,3,26,Male,No,4,0,360181.0
1806,Bachelors,2014,Bangalore,3,28,Male,No,3,0,253430.0

In [72]:
dataset.head(10)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,171369.0
1,Bachelors,2013,Pune,1,28,Female,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,166478.0
4,Masters,2017,NaN,3,24,Male,Yes,2,1,393136.0
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0,312935.0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0,364676.0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1,156724.0
8,Bachelors,2016,Pune,3,23,Male,No,1,0,52173.0
9,Masters,2017,New Delhi,2,37,Male,No,2,0,324468.0

In [74]:
dataset.tail(10)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
1797,Bachelors,2013,Pune,2,27,Female,No,5,1,59557.0
1798,Masters,2015,Bangalore,3,27,Female,No,5,0,218850.0
1799,Masters,2017,Pune,3,27,Female,No,5,1,370939.0
1800,Bachelors,2016,Bangalore,3,27,Male,No,5,0,117993.0
1801,Bachelors,2012,Bangalore,3,27,Male,No,5,0,363631.0
1802,Bachelors,2014,Bangalore,3,25,Female,No,3,0,257493.0
1803,Bachelors,2016,Bangalore,3,26,Female,No,4,0,208095.0
1804,Bachelors,2016,Bangalore,3,26,Female,No,4,0,97346.0
1805,Bachelors,2014,New Delhi,3,26,Male,No,4,0,360181.0
1806,Bachelors,2014,Bangalore,3,28,Male,No,3,0,253430.0

In [16]:
dataset.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

In [76]:
dataset.head(11)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,171369.0
1,Bachelors,2013,Pune,1,28,Female,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,166478.0
4,Masters,2017,NaN,3,24,Male,Yes,2,1,393136.0
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0,312935.0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0,364676.0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1,156724.0
8,Bachelors,2016,Pune,3,23,Male,No,1,0,52173.0
9,Masters,2017,New Delhi,2,37,Male,No,2,0,324468.0
10,Masters,2012,Bangalore,3,27,Male,No,5,1,67368.0

In [78]:
dataset[1:11]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
1,Bachelors,2013,Pune,1,28,Female,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,166478.0
4,Masters,2017,NaN,3,24,Male,Yes,2,1,393136.0
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0,312935.0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0,364676.0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1,156724.0
8,Bachelors,2016,Pune,3,23,Male,No,1,0,52173.0
9,Masters,2017,New Delhi,2,37,Male,No,2,0,324468.0
10,Masters,2012,Bangalore,3,27,Male,No,5,1,67368.0

In [80]:
dataset.tail(5)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
1802,Bachelors,2014,Bangalore,3,25,Female,No,3,0,257493.0
1803,Bachelors,2016,Bangalore,3,26,Female,No,4,0,208095.0
1804,Bachelors,2016,Bangalore,3,26,Female,No,4,0,97346.0
1805,Bachelors,2014,New Delhi,3,26,Male,No,4,0,360181.0
1806,Bachelors,2014,Bangalore,3,28,Male,No,3,0,253430.0

In [82]:
dataset.shape

(1807, 10)

In [84]:
dataset.isnull().sum()

Education                     0
JoiningYear                   0
City                         14
PaymentTier                   0
Age                           0
Gender                        8
EverBenched                   0
ExperienceInCurrentDomain     0
LeaveOrNot                    0
Salary                        9
dtype: int64

In [86]:
dataset.isnull().sum().sum()

31

In [88]:
dataset.iloc[11:20]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
11,Bachelors,2016,Pune,3,34,Male,No,3,0,NaN
12,Bachelors,2018,Pune,3,32,Male,Yes,5,1,324620.0
13,Bachelors,2016,Bangalore,3,39,Male,No,2,0,347303.0
14,Bachelors,2012,Bangalore,3,37,NaN,No,4,0,315270.0
15,Bachelors,2017,Bangalore,1,29,Male,No,3,0,144971.0
16,Bachelors,2014,NaN,3,34,Female,No,2,0,184761.0
17,Bachelors,2014,Pune,3,34,Male,No,4,0,NaN
18,Bachelors,2015,Pune,2,30,Female,No,0,1,299527.0
19,Bachelors,2016,NaN,2,22,NaN,No,0,1,245955.0

In [90]:
dataset.iloc[11:20 ,0:3]

    Education  JoiningYear       City
11  Bachelors         2016       Pune
12  Bachelors         2018       Pune
13  Bachelors         2016  Bangalore
14  Bachelors         2012  Bangalore
15  Bachelors         2017  Bangalore
16  Bachelors         2014        NaN
17  Bachelors         2014       Pune
18  Bachelors         2015       Pune
19  Bachelors         2016        NaN

In [92]:
dataset.iloc[11:20:2]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
11,Bachelors,2016,Pune,3,34,Male,No,3,0,NaN
13,Bachelors,2016,Bangalore,3,39,Male,No,2,0,347303.0
15,Bachelors,2017,Bangalore,1,29,Male,No,3,0,144971.0
17,Bachelors,2014,Pune,3,34,Male,No,4,0,NaN
19,Bachelors,2016,NaN,2,22,NaN,No,0,1,245955.0

In [94]:
dataset.iloc[[1,6,3,9,13,2],[1,4]]

    JoiningYear  Age
1          2013   28
6          2015   38
3          2016   27
9          2017   37
13         2016   39
2          2014   38

In [96]:
dataset.notnull().sum()

Education                    1807
JoiningYear                  1807
City                         1793
PaymentTier                  1807
Age                          1807
Gender                       1799
EverBenched                  1807
ExperienceInCurrentDomain    1807
LeaveOrNot                   1807
Salary                       1798
dtype: int64

In [98]:

fd=dataset.replace({"Male","Female"},{0,1})
fd

C:\Users\Victus\AppData\Local\Temp\ipykernel_17320\1603391449.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  fd=dataset.replace({"Male","Female"},{0,1})

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
0,Bachelors,2017,Bangalore,3,34,1.0,No,0,0,171369.0
1,Bachelors,2013,Pune,1,28,0.0,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,0.0,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,1.0,No,5,1,166478.0
4,Masters,2017,NaN,3,24,1.0,Yes,2,1,393136.0
...,...,...,...,...,...,...,...,...,...,...
1802,Bachelors,2014,Bangalore,3,25,0.0,No,3,0,257493.0
1803,Bachelors,2016,Bangalore,3,26,0.0,No,4,0,208095.0
1804,Bachelors,2016,Bangalore,3,26,0.0,No,4,0,97346.0
1805,Bachelors,2014,New Delhi,3,26,1.0,No,4,0,360181.0
1806,Bachelors,2014,Bangalore,3,28,1.0,No,3,0,253430.0

In [110]:
sorted_dataset = dataset.sort_values("City")
print(sorted_dataset)

      Education  JoiningYear       City  PaymentTier  Age Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34   Male          No
951   Bachelors         2014  Bangalore            3   25   Male          No
959   Bachelors         2015  Bangalore            3   26   Male          No
961         PHD         2016  Bangalore            3   27   Male          No
962   Bachelors         2018  Bangalore            3   24   Male          No
...         ...          ...        ...          ...  ...    ...         ...
1676        PHD         2017        NaN            3   27   Male          No
1690  Bachelors         2017        NaN            2   25   Male          No
1692  Bachelors         2017        NaN            3   26   Male          No
1707    Masters         2017        NaN            2   26   Male          No
1719  Bachelors         2015        NaN            3   26   Male          No

      ExperienceInCurrentDomain  LeaveOrNot    Salary
0                             0           0  171369.0
951                           3           0  179716.0
959                           4           0   96377.0
961                           5           0  216690.0
962                           2           1  364000.0
...                         ...         ...       ...
1676                          5           0  163576.0
1690                          3           1  119230.0
1692                          4           0   89346.0
1707                          4           1  134307.0
1719                          4           1   50829.0

[1807 rows x 10 columns]

In [112]:
dataset.dtypes

Education                     object
JoiningYear                    int64
City                          object
PaymentTier                    int64
Age                            int64
Gender                        object
EverBenched                   object
ExperienceInCurrentDomain      int64
LeaveOrNot                     int64
Salary                       float64
dtype: object

In [114]:

fd=dataset["Salary"]=dataset["Salary"].astype("float")
fd

0       171369.0
1       136993.0
2       113807.0
3       166478.0
4       393136.0
          ...
1802    257493.0
1803    208095.0
1804     97346.0
1805    360181.0
1806    253430.0
Name: Salary, Length: 1807, dtype: float64

In [116]:
dataset.fillna(0)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,171369.0
1,Bachelors,2013,Pune,1,28,Female,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,166478.0
4,Masters,2017,0,3,24,Male,Yes,2,1,393136.0
...,...,...,...,...,...,...,...,...,...,...
1802,Bachelors,2014,Bangalore,3,25,Female,No,3,0,257493.0
1803,Bachelors,2016,Bangalore,3,26,Female,No,4,0,208095.0
1804,Bachelors,2016,Bangalore,3,26,Female,No,4,0,97346.0
1805,Bachelors,2014,New Delhi,3,26,Male,No,4,0,360181.0
1806,Bachelors,2014,Bangalore,3,28,Male,No,3,0,253430.0

In [118]:
dataset.fillna(3)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,171369.0
1,Bachelors,2013,Pune,1,28,Female,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,166478.0
4,Masters,2017,3,3,24,Male,Yes,2,1,393136.0
...,...,...,...,...,...,...,...,...,...,...
1802,Bachelors,2014,Bangalore,3,25,Female,No,3,0,257493.0
1803,Bachelors,2016,Bangalore,3,26,Female,No,4,0,208095.0
1804,Bachelors,2016,Bangalore,3,26,Female,No,4,0,97346.0
1805,Bachelors,2014,New Delhi,3,26,Male,No,4,0,360181.0
1806,Bachelors,2014,Bangalore,3,28,Male,No,3,0,253430.0

In [120]:

dataset.describe()

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot,Salary
count,1807.000000,1807.000000,1807.000000,1807.000000,1807.000000,1798.000000
mean,2015.076923,2.695075,26.310459,3.228002,0.362479,224240.323693
std,1.854077,0.564248,2.142854,1.302112,0.480849,100823.365853
min,2012.000000,1.000000,22.000000,0.000000,0.000000,50135.000000
25%,2013.000000,2.000000,25.000000,2.000000,0.000000,137712.250000
50%,2015.000000,3.000000,26.000000,3.000000,0.000000,226605.500000
75%,2017.000000,3.000000,27.000000,4.000000,1.000000,309474.000000
max,2018.000000,3.000000,40.000000,5.000000,1.000000,399785.000000

In [122]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1807 entries, 0 to 1806
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  1807 non-null   object
 1   JoiningYear                1807 non-null   int64
 2   City                       1793 non-null   object
 3   PaymentTier                1807 non-null   int64
 4   Age                        1807 non-null   int64
 5   Gender                     1799 non-null   object
 6   EverBenched                1807 non-null   object
 7   ExperienceInCurrentDomain  1807 non-null   int64
 8   LeaveOrNot                 1807 non-null   int64
 9   Salary                     1798 non-null   float64
dtypes: float64(1), int64(5), object(4)
memory usage: 141.3+ KB

In [124]:
dataset.fillna(dataset["Age"].mean())

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,171369.0
1,Bachelors,2013,Pune,1,28,Female,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,166478.0
4,Masters,2017,26.310459,3,24,Male,Yes,2,1,393136.0
...,...,...,...,...,...,...,...,...,...,...
1802,Bachelors,2014,Bangalore,3,25,Female,No,3,0,257493.0
1803,Bachelors,2016,Bangalore,3,26,Female,No,4,0,208095.0
1804,Bachelors,2016,Bangalore,3,26,Female,No,4,0,97346.0
1805,Bachelors,2014,New Delhi,3,26,Male,No,4,0,360181.0
1806,Bachelors,2014,Bangalore,3,28,Male,No,3,0,253430.0

In [128]:
dataset.fillna(dataset["Salary"].median())

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Salary
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,171369.0
1,Bachelors,2013,Pune,1,28,Female,No,3,1,136993.0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,113807.0
3,Masters,2016,Bangalore,3,27,Male,No,5,1,166478.0
4,Masters,2017,226605.5,3,24,Male,Yes,2,1,393136.0
...,...,...,...,...,...,...,...,...,...,...
1802,Bachelors,2014,Bangalore,3,25,Female,No,3,0,257493.0
1803,Bachelors,2016,Bangalore,3,26,Female,No,4,0,208095.0
1804,Bachelors,2016,Bangalore,3,26,Female,No,4,0,97346.0
1805,Bachelors,2014,New Delhi,3,26,Male,No,4,0,360181.0
1806,Bachelors,2014,Bangalore,3,28,Male,No,3,0,253430.0

In [130]:
m=dataset["Salary"].median()
dataset["Salary"].fillna(m)

0       171369.0
1       136993.0
2       113807.0
3       166478.0
4       393136.0
          ...
1802    257493.0
1803    208095.0
1804     97346.0
1805    360181.0
1806    253430.0
Name: Salary, Length: 1807, dtype: float64

In [134]:

m=dataset["Salary"].mode()
dataset["Salary"].fillna(m)

0       171369.0
1       136993.0
2       113807.0
3       166478.0
4       393136.0
          ...
1802    257493.0
1803    208095.0
1804     97346.0
1805    360181.0
1806    253430.0
Name: Salary, Length: 1807, dtype: float64